# Generated by Django 4.2 on 2023-05-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rbd', models.IntegerField(unique=True)),
                ('digito_verificador', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=10)),
                ('oferente', models.CharField(max_length=100)),
                ('cantidad_km', models.FloatField()),
                ('alumnos', models.PositiveIntegerField()),
                ('sectores', models.CharField(max_length=200)),
                ('url_mapa', models.URLField(blank=True, null=True)),
                ('escuela', models.ManyToManyField(to='transporte.escuela')),
            ],
        ),
    ]
