# Generated by Django 4.2.1 on 2023-05-11 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rbd', models.IntegerField(unique=True)),
                ('digito_verificador', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Oferente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=10)),
                ('cantidad_km', models.FloatField()),
                ('alumnos', models.PositiveIntegerField()),
                ('sectores', models.CharField(max_length=200)),
                ('url_mapa', models.URLField(blank=True, null=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.chofer')),
                ('escuela', models.ManyToManyField(to='transporte.escuela')),
                ('oferente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.oferente')),
            ],
        ),
        migrations.AddField(
            model_name='chofer',
            name='oferente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choferes', to='transporte.oferente'),
        ),
    ]
